### ISSUE TITLE
Daemon should create socket diretory

### ISSUE THREAD

**Issue by wayneeseguin** [aurae-runtime/auraed#35]
When the daemon starts up it should check and create the configured socket directory if it doesn't exist already (ex: `/var/run/aurae`).

**Comment by MalteJ** [comment]
This should already be implemented:
https://github.com/aurae-runtime/auraed/blob/main/src/lib.rs#L101

Maybe you have started auraed without having permissions to write to `/var/run` (non-root user)?

**Comment by wayneeseguin** [comment]
I SWEAR it errored on that on Friday... super odd. Looks to be working now.
